//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingBookingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMeeting
    {
        public System.Guid MeetingId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> MeetingDtm { get; set; }
        public string Country { get; set; }
    }
}
